name: echo
version: '0.1.0.0'
category: Web
author: Eric Zoerner
maintainer: eric.zoerner@gmail.com
copyright: ! 'Copyright: (c) 2016 Eric Zoerner'
license: BSD3
github: ezoerner/echo
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
executables:
  echo-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - echo
tests:
  echo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - echo
